site_name: ControllerX

site_url: https://xaviml.github.io/controllerx/
edit_uri: edit/main/docs/docs/

repo_name: xaviml/controllerx
repo_url: https://github.com/xaviml/controllerx

copyright: Copyright &copy; Xavier Moreno

nav:
  - index.md
  - Getting started:
      - Installation: start/installation.md
      - Configuration: start/configuration.md
      - Integrations:
          - start/integrations/index.md
          - With mapping:
              - start/integrations/zigbee2mqtt.md
              - start/integrations/deconz.md
              - start/integrations/zha.md
              - start/integrations/homematic.md
              - start/integrations/lutron_caseta.md
              - start/integrations/shelly.md
              - start/integrations/shellyforhass.md
              - start/integrations/tasmota.md
          - Custom:
              - start/integrations/state.md
              - start/integrations/mqtt.md
              - start/integrations/event.md
      - Type Configuration: start/type-configuration.md
  - Supported controllers: controllers.md
  - Advanced:
      - Custom mapping:
          - advanced/index.md
          - advanced/action-types.md
          - advanced/predefined-actions.md
          - advanced/multiple-clicks.md
          - advanced/hold-click-modes.md
      - advanced/templating.md
      - advanced/entity-groups.md
      - advanced/event-integration.md
      - advanced/stateful-controllers.md
  - Examples:
      - examples/index.md
      - Others:
          - examples/sonos-display.md
          - examples/sonos.md
          - examples/tasmota-switchmode11.md
          - examples/tasmota-double-button.md
  - Others:
      - others/run-appdaemon.md
      - others/update.md
      - others/zigbee2mqtt-light-controller.md
      - others/enable-mqtt-plugin.md
      - others/z2m-ha-sensor-deprecated.md
  - faq.md

theme:
  name: material
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: material/github
  logo: assets/logo_white.png
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - macros
  - gen-files:
      scripts:
        - gen_device_pages.py
  - search:
      lang: en

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xaviml93
      name: xaviml on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/xaviml
      name: xaviml on GitHub

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - attr_list
